### ISSUE TITLE
Ignore separator and folder pages in slug generation

### ISSUE THREAD

**Issue by maechler** [wazum/sluggi#23]
TYPO3 9 by default ignores the slugs of separators and folders when generating a slug for a subpage. However the slug for separators and folders are not empty. This leads to a problem, e.g. when a subpage of a separator or folder is moved and `EXT:sluggi` automatically updates the slug.

The issue can be reproduced by the following steps:

1. Create a separator named `Separator Page`
2. Create two subpages `Test 1` and `Test 2`
3. Verify the slugs of `Test 1` and `Test 2` to be `test-1` and `test-2`
4. Change the order of the pages
5. Check the slug of the moved page, it now includes the separator page: e.g. `separator-page/test-2`

![sluggi](https://user-images.githubusercontent.com/4113819/78645867-76c29280-78b8-11ea-8f9b-855a4eb49819.gif)

**Comment by maechler** [comment]
Probably we should recursively traverse up the page tree to the first page not being a folder or a separator and then use the slug from that page, instead of just taking the slug from the parent page as base.

**Comment by wazum** [comment]
@maechler  should be fixed in 1.9.4, please test and report back, thanks!

**Comment by maechler** [comment]
@wazum Perfect, thanks! I will test it this or next week and come back to you.

**Comment by maechler** [comment]
@wazum I just tested it with `v1.9.6`, it does work now when the title is changed. However it does still not work when a page is being moved. That is because the SlugHelper is not used in `updateSlugForMovedPage`:

https://github.com/wazum/sluggi/blob/30ba9003b564791c519ca3acc69c13f991e80758/Classes/Backend/Hook/DatamapHook.php#L251

**Comment by wazum** [comment]
Thanks @maechler this is fixed in 1.9.7
