### ISSUE TITLE
Copy whole pagetree to archiv page: slugs of subpages won't update

### ISSUE THREAD

**Issue by hartundweich** [wazum/sluggi#35]
I have a typo3 website for a yearly filmfestival - when the festival is over the whole pagetree is copied to an archiv page and the actual main page is renamed.

Here is the page tree:

[1] vft
  --[2] 2020
  ---[3] program
  ---[4] jury
-- [30] archiv

When I copy the whole pagetree '2020' to archiv folder the slug of the new 2020 Page in archiv is updates as soon as I make the page visible. 
I'm expecting that the subpages 'program' and 'jury' will get updated slugs to "archiv/2020/program" and "archiv/2020/jury" but they have "2020/program-1" and "2020/jury-1"

So maybe this is a bug in sluggi or how can I get sluggi to do what I want? Copying single pages works fine - as soon as I make the copied page visible the slug is updated.

**Comment by wazum** [comment]
@hartundweich  Which version are you using (TYPO3, sluggi) and which settings are configured in the extension manager?

**Comment by hartundweich** [comment]
Typo3 9,5,19, Sluggi actual version as I wrote this issue

**Comment by wazum** [comment]
Fixed for TYPO3 CMS 9 in 1.10.3 and for TYPO3 CMS 10 in 2.0.0

**Comment by seirerman** [comment]
I still have that behaviour on TYPO3 10.4.25 and sluggi 2.1.1.

The slug of the copied page is updated, but its child pages have the old URL, but with an added "-1" at the end.

**Comment by FiveFuenf** [comment]
I also still have this problem with TYPO3 v11.5.25 and v10.4.34. See https://github.com/wazum/sluggi/issues/86.
